version "4.11"

const HDLD_GASMASK       = "dsp";
const HDLD_GASMASKFILTER = "dsf";

#include "zscript/accensus/spicyAir/sources/SpicyAirTrackers.zsc"

#include "zscript/accensus/spicyAir/SpicyAirDrug.zsc"

#include "zscript/accensus/spicyAir/items/GasMask.zsc"
#include "zscript/accensus/spicyAir/items/GasMaskFilter.zsc"

#include "zscript/accensus/spicyAir/handlers/SpicyAirHandler.zsc"

#include "zscript/accensus/spicyAir/services/SpicyAirService.zsc"
